# Generated by Django 4.1 on 2022-08-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('0', None), ('1', 'want to read'), ('2', 'reading'), ('3', 'read')], max_length=20),
        ),
    ]
